# Generated by Django 4.2.13 on 2024-05-31 16:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "idhobby",
                    models.CharField(
                        db_column="idhobby",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "Hobby",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False, null=True)),
                (
                    "iduser",
                    models.CharField(
                        db_column="iduser", default="NoIdUser", max_length=30, null=True
                    ),
                ),
                (
                    "idadmin",
                    models.CharField(
                        db_column="idadmin",
                        default="NoIdAdmin",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        default="default_avatar.jpg", null=True, upload_to=""
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.BooleanField(blank=True, default=True, null=True)),
                ("city", models.CharField(blank=True, max_length=30, null=True)),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("is_premium", models.BooleanField(default=False, null=True)),
                (
                    "premium_time",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("is_suspended", models.BooleanField(default=False, null=True)),
                (
                    "suspended_time",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "hobbies",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="Aplikacija.hobby"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "User",
                "managed": True,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Suspension",
            fields=[
                ("date", models.CharField(blank=True, max_length=30, null=True)),
                ("time", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "idsus",
                    models.CharField(
                        db_column="idsus",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idadmin",
                    models.ForeignKey(
                        blank=True,
                        db_column="idadmin",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="admin_who_suspended",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iduser",
                    models.ForeignKey(
                        blank=True,
                        db_column="iduser",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_who_recived_suspension",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Suspension",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "userR",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "idpay",
                    models.CharField(
                        db_column="idpay",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "iduser",
                    models.ForeignKey(
                        blank=True,
                        db_column="iduser",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Payment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idrep", models.CharField(db_column="idrep", max_length=30)),
                ("date", models.CharField(blank=True, max_length=30, null=True)),
                ("time", models.CharField(blank=True, max_length=30, null=True)),
                ("reason", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "iduser1",
                    models.ForeignKey(
                        db_column="iduser1",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iduser2",
                    models.ForeignKey(
                        db_column="iduser2",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Report",
                "managed": True,
                "unique_together": {("iduser1", "iduser2", "idrep")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "idmsg",
                    models.CharField(
                        db_column="idmsg",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.CharField(blank=True, max_length=30, null=True)),
                ("date", models.CharField(blank=True, max_length=30, null=True)),
                ("text", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "iduser1",
                    models.ForeignKey(
                        db_column="iduser1",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iduser2",
                    models.ForeignKey(
                        db_column="iduser2",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Message",
                "managed": True,
                "unique_together": {("iduser1", "iduser2", "idmsg")},
            },
        ),
        migrations.CreateModel(
            name="Chats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idchat", models.CharField(db_column="idchat", max_length=30)),
                (
                    "iduser1",
                    models.ForeignKey(
                        db_column="iduser1",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="chat1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iduser2",
                    models.ForeignKey(
                        db_column="iduser2",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="chat2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Chats",
                "managed": True,
                "unique_together": {("iduser1", "iduser2", "idchat")},
            },
        ),
    ]
